description: combolock

target:
  vc: msrlabs
  cluster: gcr


environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io

code:
  local_dir: $CONFIG_DIR


search:
  job_template:
    name: search_{experiment_name:s}
    sku: G1
    command:
    - cd environments/
    - python -m pip install -e . --user
    - cd ../homer_baselines/baselines
    - source setup.sh
    - python -m baselines.run --alg={alg} --env=diabcombolock --num_timesteps=1e7 --horizon={horizon} --save_path=$$PT_OUTPUT_DIR/{alg}/h={horizon}-lr={lr}-expfrac={exp_frac}-seed={seed} --log_path=$$PT_OUTPUT_DIR/{alg}/h={horizon}-lr={lr}-expfrac={exp_frac}-seed={seed} --exploration_fraction={exp_frac} 
    
  type: grid
  max_trials: 1000
  params:
    - name: seed
      spec: discrete
      values: [1, 2, 3, 4, 5]
    - name: lr
      spec: discrete
      values: [0.01, 0.001, 0.0001]
    - name: horizon
      spec: discrete
      values: [3, 6]
    - name: alg
      spec: discrete
      values: [deepq]
    - name: exp_frac
      spec: discrete
      values: [0.01, 0.001, 0.0001]      